use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelKnowledge {
    pub name: String,
    pub category: ModelCategory,
    pub description: String,
    pub trigger_tokens: Vec<String>,
    pub recommended_settings: RecommendedSettings,
    pub base_model: BaseModel,
    pub style_tags: Vec<String>,
    pub negative_prompt_suggestion: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ModelCategory {
    Anime,
    Realistic,
    Artistic,
    Photorealistic,
    Fantasy,
    Cartoon,
    PixelArt,
    InkArt,
    Cyberpunk,
    Landscape,
    Portrait,
    General,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum BaseModel {
    SD15,
    SD21,
    SDXL,
    SD3,
    Flux,
    Flux2,
    Other(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecommendedSettings {
    pub steps: u32,
    pub cfg: f64,
    pub sampler: String,
    pub scheduler: String,
    pub resolution: String,
    pub denoise: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTemplate {
    pub id: String,
    pub name: String,
    pub description: String,
    pub category: String,
    pub nodes: Vec<TemplateNode>,
    pub connections: Vec<TemplateConnection>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplateNode {
    pub id: String,
    pub class_type: String,
    pub title: String,
    pub x: i32,
    pub y: i32,
    pub inputs: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplateConnection {
    pub source: String,
    pub source_handle: String,
    pub target: String,
    pub target_handle: String,
}

pub fn get_model_knowledge_base() -> Vec<ModelKnowledge> {
    vec![
        ModelKnowledge {
            name: "Anything V5".into(),
            category: ModelCategory::Anime,
            description: "Anything V5 是一款流行的动漫风格模型，擅长生成高质量的动漫角色和场景".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["anime".into(), "illustration".into(), "2d".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "ChilloutMix".into(),
            category: ModelCategory::Photorealistic,
            description: "ChilloutMix 是一款照片级真实感模型，擅长生成亚洲风格的写实人像和照片".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["photorealistic".into(), "realistic".into(), "portrait".into(), "asian".into()],
            negative_prompt_suggestion: "paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, glans, (ugly:1.331), (duplicate:1.331), (morbid:1.21), (mutated:1.21), (bad anatomy:1.21), (bad proportions:1.331), extra limbs, (disfigured:1.331), (missing arms:1.331), (extra legs:1.331), (fused fingers:1.61051), (too many fingers:1.61051), (unclear eyes:1.331), bad hands, missing fingers, extra digit".into(),
        },
        ModelKnowledge {
            name: "DreamShaper".into(),
            category: ModelCategory::Artistic,
            description: "DreamShaper 是一款多用途模型，擅长生成艺术风格的图像，包括插画、概念艺术和幻想场景".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 30,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["artistic".into(), "illustration".into(), "concept art".into(), "fantasy".into()],
            negative_prompt_suggestion: "ugly, disfigured, deformed, bad anatomy, wrong anatomy, extra limbs, missing limbs, floating limbs, mutated hands, blurry, (mutated hands and fingers:1.2), poorly drawn face, mutation, poorly drawn, huge eyes, long body, long neck, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "GhostMix".into(),
            category: ModelCategory::Fantasy,
            description: "GhostMix 是一款混合风格模型，擅长生成幽灵般的幻想风格图像，具有独特的暗色调和神秘氛围".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["fantasy".into(), "dark".into(), "mysterious".into(), "illustration".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Deliberate".into(),
            category: ModelCategory::General,
            description: "Deliberate 是一款通用型模型，可以生成多种风格的图像，从写实到艺术风格都有不错的表现".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["versatile".into(), "general".into(), "realistic".into(), "artistic".into()],
            negative_prompt_suggestion: "ugly, tiling, poorly drawn, out of frame, deformed, body out of frame, blurry, watermark, grainy, signature, cut off, draft, deformed, disfigured, mutation, mutated, extra limbs, missing limbs, extra arms, extra legs, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, ugly, blurry, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck".into(),
        },
        ModelKnowledge {
            name: "Arcane Diffusion".into(),
            category: ModelCategory::Artistic,
            description: "Arcane Diffusion 是基于《奥术》(Arcane) 动画风格的模型，使用触发词 'arcane style' 可以获得最佳效果".into(),
            trigger_tokens: vec!["arcane style".into()],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["arcane".into(), "animated".into(), "stylized".into(), "league of legends".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Cyberpunk Anime Diffusion".into(),
            category: ModelCategory::Cyberpunk,
            description: "赛博朋克动漫风格模型，使用触发词 'dgs illustration style' 可以获得最佳效果".into(),
            trigger_tokens: vec!["dgs illustration style".into()],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["cyberpunk".into(), "anime".into(), "neon".into(), "futuristic".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Mo Di Diffusion".into(),
            category: ModelCategory::Cartoon,
            description: "现代迪士尼风格模型，使用触发词 'modern disney style' 可以获得迪士尼动画风格的效果".into(),
            trigger_tokens: vec!["modern disney style".into()],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["disney".into(), "cartoon".into(), "animated".into(), "stylized".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Inkpunk Diffusion".into(),
            category: ModelCategory::InkArt,
            description: "墨客朋克风格模型，使用触发词 'nvinkpunk style' 可以获得独特的墨水朋克风格效果".into(),
            trigger_tokens: vec!["nvinkpunk style".into()],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["inkpunk".into(), "ink".into(), "punk".into(), "illustration".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Midjourney V4 Diffusion".into(),
            category: ModelCategory::Artistic,
            description: "Midjourney V4 风格模型，使用触发词 'mdjrny-v4 style' 可以获得类似 Midjourney 的艺术效果".into(),
            trigger_tokens: vec!["mdjrny-v4 style".into()],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["midjourney".into(), "artistic".into(), "cinematic".into(), "detailed".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Papercut Diffusion".into(),
            category: ModelCategory::Artistic,
            description: "剪纸风格模型，使用触发词 'PaperCut' 可以获得精美的剪纸艺术效果".into(),
            trigger_tokens: vec!["PaperCut".into()],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["papercut".into(), "craft".into(), "artistic".into(), "paper".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Dreamlike Photoreal 2.0".into(),
            category: ModelCategory::Photorealistic,
            description: "Dreamlike Photoreal 2.0 是一款高质量的照片级真实感模型，擅长生成逼真的人物、风景和物体照片".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 30,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["photorealistic".into(), "realistic".into(), "photo".into(), "detailed".into()],
            negative_prompt_suggestion: "ugly, tiling, poorly drawn, out of frame, deformed, body out of frame, blurry, watermark, grainy, signature, cut off, draft, deformed, disfigured, mutation, mutated, extra limbs, missing limbs, extra arms, extra legs, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, ugly, blurry, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck".into(),
        },
        ModelKnowledge {
            name: "OpenJourney V4".into(),
            category: ModelCategory::Artistic,
            description: "OpenJourney V4 是一款模仿 Midjourney 风格的开源模型，使用触发词 'mdjrny-v4 style' 可以获得最佳效果".into(),
            trigger_tokens: vec!["mdjrny-v4 style".into()],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["midjourney".into(), "artistic".into(), "cinematic".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Lyriel".into(),
            category: ModelCategory::Fantasy,
            description: "Lyriel 是一款幻想风格模型，擅长生成奇幻、魔法和神话主题的图像".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["fantasy".into(), "magical".into(), "mythical".into(), "illustration".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "Realistic Vision".into(),
            category: ModelCategory::Realistic,
            description: "Realistic Vision 是一款高质量写实模型，擅长生成逼真的人物肖像和日常场景照片".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["realistic".into(), "photorealistic".into(), "portrait".into(), "photo".into()],
            negative_prompt_suggestion: "paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, glans, (ugly:1.331), (duplicate:1.331), (morbid:1.21), (mutated:1.21), (bad anatomy:1.21), (bad proportions:1.331), extra limbs, (disfigured:1.331), (missing arms:1.331), (extra legs:1.331), (fused fingers:1.61051), (too many fingers:1.61051), (unclear eyes:1.331), bad hands, missing fingers, extra digit".into(),
        },
        ModelKnowledge {
            name: "Meina Mix V8".into(),
            category: ModelCategory::Anime,
            description: "Meina Mix 是一款高质量的动漫风格混合模型，擅长生成精美的动漫角色和场景".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "euler_ancestral".into(),
                scheduler: "karras".into(),
                resolution: "512x768".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD15,
            style_tags: vec!["anime".into(), "illustration".into(), "2d".into(), "detailed".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "FLUX.1-dev".into(),
            category: ModelCategory::General,
            description: "FLUX.1 dev 是一款高质量通用模型，支持多种风格，需要配合 clip_l + t5xxl + vae 使用，推荐分辨率 1024x1024".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 20,
                cfg: 3.5,
                sampler: "euler".into(),
                scheduler: "simple".into(),
                resolution: "1024x1024".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::Flux,
            style_tags: vec!["versatile".into(), "high quality".into(), "detailed".into(), "photorealistic".into()],
            negative_prompt_suggestion: "".into(),
        },
        ModelKnowledge {
            name: "FLUX.1-schnell".into(),
            category: ModelCategory::General,
            description: "FLUX.1 schnell 是 FLUX.1 的快速推理版本，仅需4步即可生成高质量图像，需要配合 clip_l + t5xxl + vae 使用".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 4,
                cfg: 1.0,
                sampler: "euler".into(),
                scheduler: "simple".into(),
                resolution: "1024x1024".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::Flux,
            style_tags: vec!["fast".into(), "versatile".into(), "high quality".into()],
            negative_prompt_suggestion: "".into(),
        },
        ModelKnowledge {
            name: "SDXL".into(),
            category: ModelCategory::General,
            description: "Stable Diffusion XL 是一款高分辨率通用模型，推荐分辨率 1024x1024，支持多种风格".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 7.0,
                sampler: "dpmpp_2m".into(),
                scheduler: "karras".into(),
                resolution: "1024x1024".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SDXL,
            style_tags: vec!["versatile".into(), "high resolution".into(), "detailed".into()],
            negative_prompt_suggestion: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry".into(),
        },
        ModelKnowledge {
            name: "SD3 Medium".into(),
            category: ModelCategory::General,
            description: "Stable Diffusion 3 Medium 是新一代模型，需要配合 clip_l + clip_g + t5xxl 使用，推荐分辨率 1024x1024".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 25,
                cfg: 4.5,
                sampler: "euler".into(),
                scheduler: "simple".into(),
                resolution: "1024x1024".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::SD3,
            style_tags: vec!["versatile".into(), "next gen".into(), "high quality".into()],
            negative_prompt_suggestion: "".into(),
        },
        ModelKnowledge {
            name: "LTX-Video 2.3".into(),
            category: ModelCategory::General,
            description: "LTX-Video 2.3 是 Lightricks 推出的视频生成模型，支持文生视频、图生视频和音频驱动视频生成。需要配合 clip_l + t5xxl (gemma_3_12B) 文本编码器使用。支持音频 VAE 进行音频到视频的联合生成".into(),
            trigger_tokens: vec![],
            recommended_settings: RecommendedSettings {
                steps: 20,
                cfg: 1.0,
                sampler: "euler".into(),
                scheduler: "simple".into(),
                resolution: "768x512".into(),
                denoise: 1.0,
            },
            base_model: BaseModel::Other("LTX-2.3".into()),
            style_tags: vec!["video".into(), "text-to-video".into(), "image-to-video".into(), "audio-to-video".into()],
            negative_prompt_suggestion: "worst quality, low quality, blurry, distorted".into(),
        },
    ]
}

pub fn get_workflow_templates() -> Vec<WorkflowTemplate> {
    vec![
        WorkflowTemplate {
            id: "txt2img_sd15".into(),
            name: "SD 1.5 文生图".into(),
            description: "基础的 Stable Diffusion 1.5 文生图工作流".into(),
            category: "txt2img".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "CheckpointLoaderSimple".into(),
                    title: "Load Checkpoint".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"ckpt_name": ""}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 300,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 300,
                    y: 200,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "EmptyLatentImage".into(),
                    title: "Empty Latent".into(),
                    x: 300,
                    y: 350,
                    inputs: serde_json::json!({"width": 512, "height": 768, "batch_size": 1}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "KSampler".into(),
                    title: "KSampler".into(),
                    x: 600,
                    y: 150,
                    inputs: serde_json::json!({"seed": 0, "steps": 25, "cfg": 7.0, "sampler_name": "dpmpp_2m", "scheduler": "karras", "denoise": 1.0}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "VAEDecode".into(),
                    title: "VAE Decode".into(),
                    x: 900,
                    y: 150,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "7".into(),
                    class_type: "SaveImage".into(),
                    title: "Save Image".into(),
                    x: 1100,
                    y: 150,
                    inputs: serde_json::json!({"filename_prefix": "ComfyUI"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "5".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "2".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "6".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "positive".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "negative".into() },
                TemplateConnection { source: "4".into(), source_handle: "LATENT".into(), target: "5".into(), target_handle: "latent_image".into() },
                TemplateConnection { source: "5".into(), source_handle: "LATENT".into(), target: "6".into(), target_handle: "samples".into() },
                TemplateConnection { source: "6".into(), source_handle: "IMAGE".into(), target: "7".into(), target_handle: "images".into() },
            ],
        },
        WorkflowTemplate {
            id: "txt2img_flux".into(),
            name: "FLUX 文生图".into(),
            description: "FLUX.1 模型文生图工作流（使用 DualCLIPLoader + VAELoader）".into(),
            category: "txt2img".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "UNETLoader".into(),
                    title: "Load Diffusion Model".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"unet_name": "", "weight_dtype": "default"}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "DualCLIPLoader".into(),
                    title: "Load CLIP".into(),
                    x: 50,
                    y: 300,
                    inputs: serde_json::json!({"clip_name1": "", "clip_name2": "", "type": "flux"}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 300,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "EmptyLatentImage".into(),
                    title: "Empty Latent".into(),
                    x: 300,
                    y: 350,
                    inputs: serde_json::json!({"width": 1024, "height": 1024, "batch_size": 1}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "KSampler".into(),
                    title: "KSampler".into(),
                    x: 600,
                    y: 150,
                    inputs: serde_json::json!({"seed": 0, "steps": 20, "cfg": 3.5, "sampler_name": "euler", "scheduler": "simple", "denoise": 1.0}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "VAELoader".into(),
                    title: "Load VAE".into(),
                    x: 50,
                    y: 500,
                    inputs: serde_json::json!({"vae_name": ""}),
                },
                TemplateNode {
                    id: "7".into(),
                    class_type: "VAEDecode".into(),
                    title: "VAE Decode".into(),
                    x: 900,
                    y: 150,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "8".into(),
                    class_type: "SaveImage".into(),
                    title: "Save Image".into(),
                    x: 1100,
                    y: 150,
                    inputs: serde_json::json!({"filename_prefix": "ComfyUI"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "5".into(), target_handle: "model".into() },
                TemplateConnection { source: "2".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "positive".into() },
                TemplateConnection { source: "4".into(), source_handle: "LATENT".into(), target: "5".into(), target_handle: "latent_image".into() },
                TemplateConnection { source: "5".into(), source_handle: "LATENT".into(), target: "7".into(), target_handle: "samples".into() },
                TemplateConnection { source: "6".into(), source_handle: "VAE".into(), target: "7".into(), target_handle: "vae".into() },
                TemplateConnection { source: "7".into(), source_handle: "IMAGE".into(), target: "8".into(), target_handle: "images".into() },
            ],
        },
        WorkflowTemplate {
            id: "img2img_sd15".into(),
            name: "SD 1.5 图生图".into(),
            description: "Stable Diffusion 1.5 图生图工作流，基于输入图像进行修改".into(),
            category: "img2img".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "CheckpointLoaderSimple".into(),
                    title: "Load Checkpoint".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"ckpt_name": ""}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 300,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 300,
                    y: 200,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "LoadImage".into(),
                    title: "Load Image".into(),
                    x: 50,
                    y: 400,
                    inputs: serde_json::json!({"image": ""}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "VAEEncode".into(),
                    title: "VAE Encode".into(),
                    x: 300,
                    y: 400,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "KSampler".into(),
                    title: "KSampler".into(),
                    x: 600,
                    y: 150,
                    inputs: serde_json::json!({"seed": 0, "steps": 25, "cfg": 7.0, "sampler_name": "dpmpp_2m", "scheduler": "karras", "denoise": 0.6}),
                },
                TemplateNode {
                    id: "7".into(),
                    class_type: "VAEDecode".into(),
                    title: "VAE Decode".into(),
                    x: 900,
                    y: 150,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "8".into(),
                    class_type: "SaveImage".into(),
                    title: "Save Image".into(),
                    x: 1100,
                    y: 150,
                    inputs: serde_json::json!({"filename_prefix": "ComfyUI"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "6".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "2".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "5".into(), target_handle: "vae".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "7".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "CONDITIONING".into(), target: "6".into(), target_handle: "positive".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "6".into(), target_handle: "negative".into() },
                TemplateConnection { source: "4".into(), source_handle: "IMAGE".into(), target: "5".into(), target_handle: "pixels".into() },
                TemplateConnection { source: "5".into(), source_handle: "LATENT".into(), target: "6".into(), target_handle: "latent_image".into() },
                TemplateConnection { source: "6".into(), source_handle: "LATENT".into(), target: "7".into(), target_handle: "samples".into() },
                TemplateConnection { source: "7".into(), source_handle: "IMAGE".into(), target: "8".into(), target_handle: "images".into() },
            ],
        },
        WorkflowTemplate {
            id: "txt2img_sdxl".into(),
            name: "SDXL 文生图".into(),
            description: "Stable Diffusion XL 文生图工作流（使用 DualCLIPLoader）".into(),
            category: "txt2img".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "CheckpointLoaderSimple".into(),
                    title: "Load Checkpoint".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"ckpt_name": ""}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 300,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 300,
                    y: 200,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "EmptyLatentImage".into(),
                    title: "Empty Latent".into(),
                    x: 300,
                    y: 350,
                    inputs: serde_json::json!({"width": 1024, "height": 1024, "batch_size": 1}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "KSampler".into(),
                    title: "KSampler".into(),
                    x: 600,
                    y: 150,
                    inputs: serde_json::json!({"seed": 0, "steps": 25, "cfg": 7.0, "sampler_name": "dpmpp_2m", "scheduler": "karras", "denoise": 1.0}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "VAEDecode".into(),
                    title: "VAE Decode".into(),
                    x: 900,
                    y: 150,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "7".into(),
                    class_type: "SaveImage".into(),
                    title: "Save Image".into(),
                    x: 1100,
                    y: 150,
                    inputs: serde_json::json!({"filename_prefix": "ComfyUI"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "5".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "2".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "6".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "positive".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "negative".into() },
                TemplateConnection { source: "4".into(), source_handle: "LATENT".into(), target: "5".into(), target_handle: "latent_image".into() },
                TemplateConnection { source: "5".into(), source_handle: "LATENT".into(), target: "6".into(), target_handle: "samples".into() },
                TemplateConnection { source: "6".into(), source_handle: "IMAGE".into(), target: "7".into(), target_handle: "images".into() },
            ],
        },
        WorkflowTemplate {
            id: "upscale_esrgan".into(),
            name: "ESRGAN 放大".into(),
            description: "使用 ESRGAN 模型进行图像超分辨率放大".into(),
            category: "upscale".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "LoadImage".into(),
                    title: "Load Image".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"image": ""}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "UpscaleModelLoader".into(),
                    title: "Load Upscale Model".into(),
                    x: 50,
                    y: 300,
                    inputs: serde_json::json!({"model_name": ""}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "ImageUpscaleWithModel".into(),
                    title: "Upscale Image".into(),
                    x: 350,
                    y: 150,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "SaveImage".into(),
                    title: "Save Image".into(),
                    x: 650,
                    y: 150,
                    inputs: serde_json::json!({"filename_prefix": "Upscaled"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "IMAGE".into(), target: "3".into(), target_handle: "image".into() },
                TemplateConnection { source: "2".into(), source_handle: "UPSCALE_MODEL".into(), target: "3".into(), target_handle: "upscale_model".into() },
                TemplateConnection { source: "3".into(), source_handle: "IMAGE".into(), target: "4".into(), target_handle: "images".into() },
            ],
        },
        WorkflowTemplate {
            id: "wan_txt2vid".into(),
            name: "Wan2.1 文生视频".into(),
            description: "使用 Wan2.1 模型从文本生成视频".into(),
            category: "video".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "WanLoader".into(),
                    title: "Load Wan Model".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"model_name": ""}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 350,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 350,
                    y: 200,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "WanVideoSampler".into(),
                    title: "Wan Video Sampler".into(),
                    x: 650,
                    y: 100,
                    inputs: serde_json::json!({"seed": 42, "steps": 20, "cfg": 6.0, "sampler_name": "euler", "scheduler": "discrete", "width": 832, "height": 480, "video_frames": 33}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "VideoVAEDecode".into(),
                    title: "Video VAE Decode".into(),
                    x: 950,
                    y: 100,
                    inputs: serde_json::json!({"fps": 8}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "SaveVideo".into(),
                    title: "Save Video".into(),
                    x: 1200,
                    y: 100,
                    inputs: serde_json::json!({"filename_prefix": "WanVideo", "fps": 8, "format": "mp4"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "4".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "2".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "5".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "CONDITIONING".into(), target: "4".into(), target_handle: "positive".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "4".into(), target_handle: "negative".into() },
                TemplateConnection { source: "4".into(), source_handle: "LATENT".into(), target: "5".into(), target_handle: "samples".into() },
                TemplateConnection { source: "5".into(), source_handle: "VIDEO".into(), target: "6".into(), target_handle: "video".into() },
            ],
        },
        WorkflowTemplate {
            id: "wan_img2vid".into(),
            name: "Wan2.1 图生视频".into(),
            description: "使用 Wan2.1 模型从图片生成视频（首帧引导）".into(),
            category: "video".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "WanLoader".into(),
                    title: "Load Wan Model".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"model_name": ""}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "LoadImage".into(),
                    title: "Load Init Image".into(),
                    x: 50,
                    y: 350,
                    inputs: serde_json::json!({"image": ""}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 350,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 350,
                    y: 200,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "WanVideoSampler".into(),
                    title: "Wan Video Sampler".into(),
                    x: 650,
                    y: 100,
                    inputs: serde_json::json!({"seed": 42, "steps": 20, "cfg": 6.0, "sampler_name": "euler", "scheduler": "discrete", "width": 832, "height": 480, "video_frames": 33}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "VideoVAEDecode".into(),
                    title: "Video VAE Decode".into(),
                    x: 950,
                    y: 100,
                    inputs: serde_json::json!({"fps": 8}),
                },
                TemplateNode {
                    id: "7".into(),
                    class_type: "SaveVideo".into(),
                    title: "Save Video".into(),
                    x: 1200,
                    y: 100,
                    inputs: serde_json::json!({"filename_prefix": "WanImg2Vid", "fps": 8, "format": "mp4"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "5".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "4".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "6".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "IMAGE".into(), target: "5".into(), target_handle: "init_image".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "positive".into() },
                TemplateConnection { source: "4".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "negative".into() },
                TemplateConnection { source: "5".into(), source_handle: "LATENT".into(), target: "6".into(), target_handle: "samples".into() },
                TemplateConnection { source: "6".into(), source_handle: "VIDEO".into(), target: "7".into(), target_handle: "video".into() },
            ],
        },
        WorkflowTemplate {
            id: "ltx_txt2vid".into(),
            name: "LTX 文生视频".into(),
            description: "使用 LTX-Video 模型从文本生成视频".into(),
            category: "video".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "LTXLoader".into(),
                    title: "Load LTX Model".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"model_name": ""}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 350,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 350,
                    y: 200,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "LTXVideoSampler".into(),
                    title: "LTX Video Sampler".into(),
                    x: 650,
                    y: 100,
                    inputs: serde_json::json!({"seed": 42, "steps": 20, "cfg": 3.0, "sampler_name": "euler", "scheduler": "normal", "width": 768, "height": 512, "video_frames": 97, "num_frames_per_seed": 1}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "VideoVAEDecode".into(),
                    title: "Video VAE Decode".into(),
                    x: 950,
                    y: 100,
                    inputs: serde_json::json!({"fps": 8}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "SaveVideo".into(),
                    title: "Save Video".into(),
                    x: 1200,
                    y: 100,
                    inputs: serde_json::json!({"filename_prefix": "LTXVideo", "fps": 8, "format": "mp4"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "4".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "2".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "5".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "CONDITIONING".into(), target: "4".into(), target_handle: "positive".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "4".into(), target_handle: "negative".into() },
                TemplateConnection { source: "4".into(), source_handle: "LATENT".into(), target: "5".into(), target_handle: "samples".into() },
                TemplateConnection { source: "5".into(), source_handle: "VIDEO".into(), target: "6".into(), target_handle: "video".into() },
            ],
        },
        WorkflowTemplate {
            id: "ltx23_i2v".into(),
            name: "LTX-2.3 图生视频".into(),
            description: "使用 LTX-Video 2.3 模型从图片生成视频，支持高级采样器配置".into(),
            category: "video".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "LTXLoader".into(),
                    title: "Load LTX Model".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"model_name": "ltx-2.3-22b-dev-fp8.safetensors"}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "LTXAVTextEncoderLoader".into(),
                    title: "Load LTX Text Encoder".into(),
                    x: 50,
                    y: 300,
                    inputs: serde_json::json!({"text_encoder": "gemma_3_12B_it_fp4_mixed.safetensors", "ckpt_name": "ltx-2.3-22b-dev-fp8.safetensors"}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 350,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 350,
                    y: 200,
                    inputs: serde_json::json!({"text": "worst quality, low quality"}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "LTXVConditioning".into(),
                    title: "LTXV Conditioning".into(),
                    x: 650,
                    y: 100,
                    inputs: serde_json::json!({"frame_rate": 25.0}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "LoadImage".into(),
                    title: "Load Image".into(),
                    x: 50,
                    y: 500,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "7".into(),
                    class_type: "LTXVPreprocess".into(),
                    title: "LTXV Preprocess".into(),
                    x: 350,
                    y: 500,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "8".into(),
                    class_type: "EmptyLTXVLatentVideo".into(),
                    title: "Empty LTXV Latent Video".into(),
                    x: 350,
                    y: 700,
                    inputs: serde_json::json!({"width": 768, "height": 512, "length": 97, "batch_size": 1}),
                },
                TemplateNode {
                    id: "9".into(),
                    class_type: "LTXVImgToVideoInplace".into(),
                    title: "LTXV Image to Video".into(),
                    x: 650,
                    y: 500,
                    inputs: serde_json::json!({"bypass": false}),
                },
                TemplateNode {
                    id: "10".into(),
                    class_type: "RandomNoise".into(),
                    title: "Random Noise".into(),
                    x: 650,
                    y: 700,
                    inputs: serde_json::json!({"noise_seed": 0, "control_after_generate": "randomize"}),
                },
                TemplateNode {
                    id: "11".into(),
                    class_type: "CFGGuider".into(),
                    title: "CFG Guider".into(),
                    x: 950,
                    y: 100,
                    inputs: serde_json::json!({"cfg": 1.0}),
                },
                TemplateNode {
                    id: "12".into(),
                    class_type: "KSamplerSelect".into(),
                    title: "KSampler Select".into(),
                    x: 950,
                    y: 300,
                    inputs: serde_json::json!({"sampler_name": "euler"}),
                },
                TemplateNode {
                    id: "13".into(),
                    class_type: "ManualSigmas".into(),
                    title: "Manual Sigmas".into(),
                    x: 950,
                    y: 500,
                    inputs: serde_json::json!({"sigmas": "1.0, 0.0"}),
                },
                TemplateNode {
                    id: "14".into(),
                    class_type: "SamplerCustomAdvanced".into(),
                    title: "Sampler Custom Advanced".into(),
                    x: 1250,
                    y: 300,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "15".into(),
                    class_type: "LTXVSeparateAVLatent".into(),
                    title: "LTXV Separate AV Latent".into(),
                    x: 1550,
                    y: 200,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "16".into(),
                    class_type: "VAEDecodeTiled".into(),
                    title: "VAE Decode Tiled".into(),
                    x: 1850,
                    y: 200,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "17".into(),
                    class_type: "CreateVideo".into(),
                    title: "Create Video".into(),
                    x: 2150,
                    y: 200,
                    inputs: serde_json::json!({"fps": 25.0}),
                },
                TemplateNode {
                    id: "18".into(),
                    class_type: "SaveVideo".into(),
                    title: "Save Video".into(),
                    x: 2450,
                    y: 200,
                    inputs: serde_json::json!({"filename_prefix": "LTX23_i2v", "fps": 25, "format": "mp4"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "11".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "9".into(), target_handle: "vae".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "16".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "CLIP".into(), target: "3".into(), target_handle: "clip".into() },
                TemplateConnection { source: "2".into(), source_handle: "CLIP".into(), target: "4".into(), target_handle: "clip".into() },
                TemplateConnection { source: "3".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "positive".into() },
                TemplateConnection { source: "4".into(), source_handle: "CONDITIONING".into(), target: "5".into(), target_handle: "negative".into() },
                TemplateConnection { source: "5".into(), source_handle: "positive".into(), target: "11".into(), target_handle: "positive".into() },
                TemplateConnection { source: "5".into(), source_handle: "negative".into(), target: "11".into(), target_handle: "negative".into() },
                TemplateConnection { source: "6".into(), source_handle: "IMAGE".into(), target: "7".into(), target_handle: "image".into() },
                TemplateConnection { source: "7".into(), source_handle: "output_image".into(), target: "9".into(), target_handle: "image".into() },
                TemplateConnection { source: "8".into(), source_handle: "LATENT".into(), target: "9".into(), target_handle: "latent".into() },
                TemplateConnection { source: "9".into(), source_handle: "latent".into(), target: "14".into(), target_handle: "latent_image".into() },
                TemplateConnection { source: "10".into(), source_handle: "NOISE".into(), target: "14".into(), target_handle: "noise".into() },
                TemplateConnection { source: "11".into(), source_handle: "GUIDER".into(), target: "14".into(), target_handle: "guider".into() },
                TemplateConnection { source: "12".into(), source_handle: "SAMPLER".into(), target: "14".into(), target_handle: "sampler".into() },
                TemplateConnection { source: "13".into(), source_handle: "SIGMAS".into(), target: "14".into(), target_handle: "sigmas".into() },
                TemplateConnection { source: "14".into(), source_handle: "output".into(), target: "15".into(), target_handle: "av_latent".into() },
                TemplateConnection { source: "15".into(), source_handle: "video_latent".into(), target: "16".into(), target_handle: "samples".into() },
                TemplateConnection { source: "16".into(), source_handle: "IMAGE".into(), target: "17".into(), target_handle: "images".into() },
                TemplateConnection { source: "17".into(), source_handle: "VIDEO".into(), target: "18".into(), target_handle: "video".into() },
            ],
        },
        WorkflowTemplate {
            id: "ltx23_ia2v".into(),
            name: "LTX-2.3 音频驱动视频生成".into(),
            description: "使用 LTX-Video 2.3 模型从图片和音频生成视频，支持音频驱动的视频生成".into(),
            category: "video".into(),
            nodes: vec![
                TemplateNode {
                    id: "1".into(),
                    class_type: "LTXLoader".into(),
                    title: "Load LTX Model".into(),
                    x: 50,
                    y: 100,
                    inputs: serde_json::json!({"model_name": "ltx-2.3-22b-dev-fp8.safetensors"}),
                },
                TemplateNode {
                    id: "2".into(),
                    class_type: "LTXAVTextEncoderLoader".into(),
                    title: "Load LTX Text Encoder".into(),
                    x: 50,
                    y: 300,
                    inputs: serde_json::json!({"text_encoder": "gemma_3_12B_it_fp4_mixed.safetensors", "ckpt_name": "ltx-2.3-22b-dev-fp8.safetensors"}),
                },
                TemplateNode {
                    id: "3".into(),
                    class_type: "LTXVAudioVAELoader".into(),
                    title: "Load LTX Audio VAE".into(),
                    x: 50,
                    y: 500,
                    inputs: serde_json::json!({"ckpt_name": "ltx-2.3-22b-dev-fp8.safetensors"}),
                },
                TemplateNode {
                    id: "4".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Positive Prompt".into(),
                    x: 350,
                    y: 50,
                    inputs: serde_json::json!({"text": ""}),
                },
                TemplateNode {
                    id: "5".into(),
                    class_type: "CLIPTextEncode".into(),
                    title: "Negative Prompt".into(),
                    x: 350,
                    y: 200,
                    inputs: serde_json::json!({"text": "worst quality, low quality"}),
                },
                TemplateNode {
                    id: "6".into(),
                    class_type: "LTXVConditioning".into(),
                    title: "LTXV Conditioning".into(),
                    x: 650,
                    y: 100,
                    inputs: serde_json::json!({"frame_rate": 25.0}),
                },
                TemplateNode {
                    id: "7".into(),
                    class_type: "LoadImage".into(),
                    title: "Load Image".into(),
                    x: 50,
                    y: 700,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "8".into(),
                    class_type: "LTXVPreprocess".into(),
                    title: "LTXV Preprocess".into(),
                    x: 350,
                    y: 700,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "9".into(),
                    class_type: "EmptyLTXVLatentVideo".into(),
                    title: "Empty LTXV Latent Video".into(),
                    x: 350,
                    y: 900,
                    inputs: serde_json::json!({"width": 768, "height": 512, "length": 97, "batch_size": 1}),
                },
                TemplateNode {
                    id: "10".into(),
                    class_type: "LTXVImgToVideoInplace".into(),
                    title: "LTXV Image to Video".into(),
                    x: 650,
                    y: 700,
                    inputs: serde_json::json!({"bypass": false}),
                },
                TemplateNode {
                    id: "11".into(),
                    class_type: "LoadAudio".into(),
                    title: "Load Audio".into(),
                    x: 50,
                    y: 900,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "12".into(),
                    class_type: "TrimAudioDuration".into(),
                    title: "Trim Audio".into(),
                    x: 350,
                    y: 1100,
                    inputs: serde_json::json!({"start_index": 0.0, "duration": 60.0}),
                },
                TemplateNode {
                    id: "13".into(),
                    class_type: "LTXVAudioVAEEncode".into(),
                    title: "LTXV Audio VAE Encode".into(),
                    x: 650,
                    y: 900,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "14".into(),
                    class_type: "LTXVEmptyLatentAudio".into(),
                    title: "Empty LTXV Latent Audio".into(),
                    x: 650,
                    y: 1100,
                    inputs: serde_json::json!({"frames_number": 97, "frame_rate": 25, "batch_size": 1}),
                },
                TemplateNode {
                    id: "15".into(),
                    class_type: "LTXVConcatAVLatent".into(),
                    title: "LTXV Concat AV Latent".into(),
                    x: 950,
                    y: 700,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "16".into(),
                    class_type: "RandomNoise".into(),
                    title: "Random Noise".into(),
                    x: 950,
                    y: 900,
                    inputs: serde_json::json!({"noise_seed": 0, "control_after_generate": "randomize"}),
                },
                TemplateNode {
                    id: "17".into(),
                    class_type: "CFGGuider".into(),
                    title: "CFG Guider".into(),
                    x: 1250,
                    y: 100,
                    inputs: serde_json::json!({"cfg": 1.0}),
                },
                TemplateNode {
                    id: "18".into(),
                    class_type: "KSamplerSelect".into(),
                    title: "KSampler Select".into(),
                    x: 1250,
                    y: 300,
                    inputs: serde_json::json!({"sampler_name": "euler"}),
                },
                TemplateNode {
                    id: "19".into(),
                    class_type: "ManualSigmas".into(),
                    title: "Manual Sigmas".into(),
                    x: 1250,
                    y: 500,
                    inputs: serde_json::json!({"sigmas": "1.0, 0.0"}),
                },
                TemplateNode {
                    id: "20".into(),
                    class_type: "SamplerCustomAdvanced".into(),
                    title: "Sampler Custom Advanced".into(),
                    x: 1550,
                    y: 500,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "21".into(),
                    class_type: "LTXVSeparateAVLatent".into(),
                    title: "LTXV Separate AV Latent".into(),
                    x: 1850,
                    y: 400,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "22".into(),
                    class_type: "VAEDecodeTiled".into(),
                    title: "VAE Decode Tiled".into(),
                    x: 2150,
                    y: 300,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "23".into(),
                    class_type: "LTXVAudioVAEDecode".into(),
                    title: "LTXV Audio VAE Decode".into(),
                    x: 2150,
                    y: 500,
                    inputs: serde_json::json!({}),
                },
                TemplateNode {
                    id: "24".into(),
                    class_type: "CreateVideo".into(),
                    title: "Create Video".into(),
                    x: 2450,
                    y: 300,
                    inputs: serde_json::json!({"fps": 25.0}),
                },
                TemplateNode {
                    id: "25".into(),
                    class_type: "SaveVideo".into(),
                    title: "Save Video".into(),
                    x: 2750,
                    y: 300,
                    inputs: serde_json::json!({"filename_prefix": "LTX23_ia2v", "fps": 25, "format": "mp4"}),
                },
                TemplateNode {
                    id: "26".into(),
                    class_type: "SaveAudio".into(),
                    title: "Save Audio".into(),
                    x: 2450,
                    y: 500,
                    inputs: serde_json::json!({"filename_prefix": "LTX23_ia2v_audio"}),
                },
            ],
            connections: vec![
                TemplateConnection { source: "1".into(), source_handle: "MODEL".into(), target: "17".into(), target_handle: "model".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "10".into(), target_handle: "vae".into() },
                TemplateConnection { source: "1".into(), source_handle: "VAE".into(), target: "22".into(), target_handle: "vae".into() },
                TemplateConnection { source: "2".into(), source_handle: "CLIP".into(), target: "4".into(), target_handle: "clip".into() },
                TemplateConnection { source: "2".into(), source_handle: "CLIP".into(), target: "5".into(), target_handle: "clip".into() },
                TemplateConnection { source: "3".into(), source_handle: "Audio VAE".into(), target: "13".into(), target_handle: "audio_vae".into() },
                TemplateConnection { source: "3".into(), source_handle: "Audio VAE".into(), target: "14".into(), target_handle: "audio_vae".into() },
                TemplateConnection { source: "3".into(), source_handle: "Audio VAE".into(), target: "23".into(), target_handle: "audio_vae".into() },
                TemplateConnection { source: "4".into(), source_handle: "CONDITIONING".into(), target: "6".into(), target_handle: "positive".into() },
                TemplateConnection { source: "5".into(), source_handle: "CONDITIONING".into(), target: "6".into(), target_handle: "negative".into() },
                TemplateConnection { source: "6".into(), source_handle: "positive".into(), target: "17".into(), target_handle: "positive".into() },
                TemplateConnection { source: "6".into(), source_handle: "negative".into(), target: "17".into(), target_handle: "negative".into() },
                TemplateConnection { source: "7".into(), source_handle: "IMAGE".into(), target: "8".into(), target_handle: "image".into() },
                TemplateConnection { source: "8".into(), source_handle: "output_image".into(), target: "10".into(), target_handle: "image".into() },
                TemplateConnection { source: "9".into(), source_handle: "LATENT".into(), target: "10".into(), target_handle: "latent".into() },
                TemplateConnection { source: "10".into(), source_handle: "latent".into(), target: "15".into(), target_handle: "video_latent".into() },
                TemplateConnection { source: "11".into(), source_handle: "AUDIO".into(), target: "12".into(), target_handle: "audio".into() },
                TemplateConnection { source: "12".into(), source_handle: "AUDIO".into(), target: "13".into(), target_handle: "audio".into() },
                TemplateConnection { source: "13".into(), source_handle: "Audio Latent".into(), target: "15".into(), target_handle: "audio_latent".into() },
                TemplateConnection { source: "14".into(), source_handle: "Latent".into(), target: "15".into(), target_handle: "audio_latent".into() },
                TemplateConnection { source: "15".into(), source_handle: "latent".into(), target: "20".into(), target_handle: "latent_image".into() },
                TemplateConnection { source: "16".into(), source_handle: "NOISE".into(), target: "20".into(), target_handle: "noise".into() },
                TemplateConnection { source: "17".into(), source_handle: "GUIDER".into(), target: "20".into(), target_handle: "guider".into() },
                TemplateConnection { source: "18".into(), source_handle: "SAMPLER".into(), target: "20".into(), target_handle: "sampler".into() },
                TemplateConnection { source: "19".into(), source_handle: "SIGMAS".into(), target: "20".into(), target_handle: "sigmas".into() },
                TemplateConnection { source: "20".into(), source_handle: "output".into(), target: "21".into(), target_handle: "av_latent".into() },
                TemplateConnection { source: "21".into(), source_handle: "video_latent".into(), target: "22".into(), target_handle: "samples".into() },
                TemplateConnection { source: "21".into(), source_handle: "audio_latent".into(), target: "23".into(), target_handle: "samples".into() },
                TemplateConnection { source: "22".into(), source_handle: "IMAGE".into(), target: "24".into(), target_handle: "images".into() },
                TemplateConnection { source: "23".into(), source_handle: "Audio".into(), target: "24".into(), target_handle: "audio".into() },
                TemplateConnection { source: "24".into(), source_handle: "VIDEO".into(), target: "25".into(), target_handle: "video".into() },
                TemplateConnection { source: "23".into(), source_handle: "Audio".into(), target: "26".into(), target_handle: "audio".into() },
            ],
        },
    ]
}

pub fn get_models_by_category(category: &ModelCategory) -> Vec<ModelKnowledge> {
    get_model_knowledge_base()
        .into_iter()
        .filter(|m| m.category == *category)
        .collect()
}

pub fn get_models_by_style(style: &str) -> Vec<ModelKnowledge> {
    let style_lower = style.to_lowercase();
    get_model_knowledge_base()
        .into_iter()
        .filter(|m| {
            m.style_tags.iter().any(|t| t.to_lowercase().contains(&style_lower))
                || m.name.to_lowercase().contains(&style_lower)
                || m.description.to_lowercase().contains(&style_lower)
        })
        .collect()
}

pub fn get_template_by_id(id: &str) -> Option<WorkflowTemplate> {
    get_workflow_templates().into_iter().find(|t| t.id == id)
}

pub fn get_templates_by_category(category: &str) -> Vec<WorkflowTemplate> {
    get_workflow_templates()
        .into_iter()
        .filter(|t| t.category == category)
        .collect()
}
